---
title: "baselines_recid_broward"
author: "Beau Coker"
date: "11/5/2018"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(warning=F, message=F,echo = TRUE)
knitr::opts_knit$set(root.dir = '/tmp')
```


```{r include = FALSE}
library(tidyverse)
library(magrittr)
require(caret)
```


```{r}
data_path = "C:/Users/binha/Documents/Duke/Cynthia Research/KY-analysis-mytrials/broward/data/"
load(paste0(data_path, "compas_psa.Rdata"))
load(paste0(data_path, "expanded_features.Rdata"))
labels = read_csv("~/Duke/Cynthia Research/KY-analysis-mytrials/broward/data/labels.csv") %>% 
    mutate(screening_date = as.Date(screening_date, format = "%m/%d/%Y"))
```


## smaller set with psa features
```{r}
### Add useful columns to features and apply row filters used for all models
features_filt = features_before_on %>%
  select(-p_incarceration) %>% 
  inner_join(
    data_before %>% 
      select(person_id, screening_date, people) %>%
      unnest() %>%
      select(person_id, screening_date, race, sex, name),
    by = c("person_id","screening_date")
  ) %>%
  mutate(sex = ifelse(sex == "Male", 1, 0)) %>% #change sex variable to numeric encoding
  inner_join(features_on, by = c("person_id","screening_date")) %>%
    inner_join(
        psa_features%>%
            select(-c(p_current_age, p_prison)), 
        by = c("person_id","screening_date")) %>%
    inner_join(outcomes, by = c("person_id","screening_date")) %>%
    inner_join(
        features %>% 
            select(person_id, screening_date, p_incarceration, years_since_last_crime, six_month, 
                   one_year, three_year, five_year), 
        by = c("person_id", "screening_date")) %>% 
  filter(`Risk of Recidivism_decile_score` != -1, `Risk of Violence_decile_score` != -1) %>% # Filter 1
  filter(!is.na(current_offense_date)) %>% # Filter 3
  filter(screening_date <= current_offense_date_limit) %>% # Filter 4
  mutate(decile_use = `Risk of Recidivism_decile_score`) # Select recidivism or violent recidivism decile score to use in this script
```



```{r}
###########################################################
## PSA available set
df_psa = features_filt %>%
  transmute(
    person_id,
    sex,
    race,
    screening_date,
    
    #COMPAS Risk of Recidivism Features\
    age_at_current_charge,
    age_at_first_charge,
    p_charges,
    p_incarceration = p_incarceration,
    p_probation = p_probation,
    
    #COMPAS Risk of violent recidivism features
    p_juv_fel_count,
    p_felprop_viol,
    p_murder,
    p_felassault,
    p_misdeassault,
    p_famviol,
    p_sex_offense,
    p_weapon,
    
    #PSA Features (which were not named above)
    fail_appear_two_yr, 
    fail_appear_two_plus,
    current_violent, 
    current_violent20, 
    pending_charge, 
    prior_conviction_F, 
    prior_conviction_M, 
    violent_conviction, 
    total_convictions, 
    
    #Misc Features
    p_arrest,
    p_property,
    p_traffic,
    p_drug,
    p_dui,
    p_domestic,
    p_stalking,
    p_voyeurism,
    p_fraud,
    p_stealing,
    p_trespass,
    six_month,
    one_year,
    three_year,
    five_year) %>%
  rename(p_fta_two_year = fail_appear_two_yr,
         p_fta_two_year_plus = fail_appear_two_plus,
         current_violence = current_violent,
         current_violence20 = current_violent20,
         p_pending_charge = pending_charge,
         p_felony = prior_conviction_F,
         p_misdemeanor = prior_conviction_M,
         p_violence = violent_conviction) %>% 
  na.omit()
```


## combine data sets

```{r}
colnames(labels)
```


```{r}
## merge df with labels
df_psa = merge(x=df_psa, y =labels, by=c('person_id', 'screening_date'))%>% 
    select(person_id:general_six_month, 
           drug_two_year, 
           property_two_year,
           misdemeanor_two_year,
           felony_two_year,
           violent_two_year,           
           drug_six_month, 
           property_six_month,
           misdemeanor_six_month,
           felony_six_month,
           violent_six_month) %>% 
    mutate(general_two_year = as.factor(general_two_year),
           drug_two_year = as.factor(drug_two_year),
           property_two_year = as.factor(property_two_year),
           felony_two_year = as.factor(felony_two_year),
           misdemeanor_two_year = as.factor(misdemeanor_two_year),
           violent_two_year = as.factor(violent_two_year),
           general_six_month = as.factor(general_six_month),
           drug_six_month = as.factor(drug_six_month),
           property_six_month = as.factor(property_six_month),
           felony_six_month = as.factor(felony_six_month),
           misdemeanor_six_month = as.factor(misdemeanor_six_month),
           violent_six_month = as.factor(violent_six_month))
```


```{r}
## compass & arnold
scores_outcomes = compas_psa_wide %>%
  filter(`Risk of Violence_decile_score`>=0, 
         `Risk of Recidivism_decile_score`>=0, 
         `Risk of Failure to Appear_decile_score`>=0) %>%
  left_join(outcomes, by=c("person_id","screening_date")) %>%
  merge(x=., y=df_psa %>% select(person_id, screening_date, sex, race, 
                             age_at_current_charge, p_charges), 
        by = c("person_id", "screening_date")) 
```



```{r}
### split train and test for those models with 5-general-CV
set.seed(816)
psa_test_sample = sample(1:nrow(df_psa), 0.2*nrow(df_psa), replace = FALSE)
psa_test = df_psa[psa_test_sample,]
psa_train = df_psa[-psa_test_sample, ]
arnold_test = scores_outcomes[psa_test_sample, ]
arnold_train = scores_outcomes[-psa_test_sample, ]

```

## save data
```{r}
## psa subset
write.csv(df_psa, file = "broward_data.csv", row.names = F)
write.csv(psa_train, file = "broward_train.csv", row.names = F)
write.csv(psa_test, file = "broward_test.csv", row.names = F)

## psa scores
write.csv(scores_outcomes, file = "broward_arnold.csv", row.names = F)
write.csv(arnold_train, file = "broward_arnold_train.csv", row.names = F)
write.csv(arnold_test, file = "broward_arnold_test.csv", row.names = F)

## index
#write.csv(psa_test_sample, file = "broward_test_index.csv", row.names = F)
```










### appendix -- full data
```{r}
###########################################################
df_full = features_filt %>%
  transmute(
    person_id,
    sex,
    race,
    screening_date,
    
    #COMPAS Risk of Recidivism Features\
    age_at_current_charge,
    age_at_first_charge,
    p_charges,
    p_incarceration = p_incarceration,
    p_probation = p_probation,
    
    #COMPAS Risk of violent recidivism features
    p_juv_fel_count,
    p_felprop_viol,
    p_murder,
    p_felassault,
    p_misdeassault,
    p_famviol,
    p_sex_offense,
    p_weapon,
    
    #Misc Features
    p_arrest,
    p_property,
    p_traffic,
    p_drug,
    p_dui,
    p_domestic,
    p_stalking,
    p_voyeurism,
    p_fraud,
    p_stealing,
    p_trespass,
    six_month,
    one_year,
    three_year,
    five_year) %>%
  na.omit()
```

```{r}
#### full
df_full = merge(x=df_full, y =labels, by=c('person_id', 'screening_date'))%>% 
    select(person_id:general_six_month, 
           drug_two_year, 
           property_two_year,
           misdemeanor_two_year,
           felony_two_year,
           violent_two_year,           
           drug_six_month, 
           property_six_month,
           misdemeanor_six_month,
           felony_six_month,
           violent_six_month)%>% 
    mutate(general_two_year = as.factor(general_two_year),
           drug_two_year = as.factor(drug_two_year),
           property_two_year = as.factor(property_two_year),
           felony_two_year = as.factor(felony_two_year),
           misdemeanor_two_year = as.factor(misdemeanor_two_year),
           violent_two_year = as.factor(violent_two_year),
           general_six_month = as.factor(general_six_month),
           drug_six_month = as.factor(drug_six_month),
           property_six_month = as.factor(property_six_month),
           felony_six_month = as.factor(felony_six_month),
           misdemeanor_six_month = as.factor(misdemeanor_six_month),
           violent_six_month = as.factor(violent_six_month))
```


```{r}
### 
full_test_sample = sample(1:nrow(df_full), 0.2*nrow(df_full), replace = FALSE)
full_test = df_full[full_test_sample, ]
full_train = df_full[-full_test_sample, ]

## full data
write.csv(df_full, file = "broward_full_data.csv", row.names = F)
write.csv(full_train, file = "broward_full_train.csv", row.names = F)
write.csv(full_test, file = "broward_full_test.csv", row.names = F)
```


